table calendario
	lineageTag: 3b7f8e08-ef79-4625-b5f7-d0ced564775a
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 1596d554-8b4e-467f-b9fe-2d4263241e3f
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 52035ddb-2ea7-4aa5-b84e-e82e7a3be609
		summarizeBy: none
		sourceColumn: Ano

	column 'Mês Nº'
		dataType: int64
		formatString: 0
		lineageTag: 1fd1cce4-c2c4-49f5-8d0a-7cdc0d0ff203
		summarizeBy: none
		sourceColumn: Mês Nº

	column Mês
		dataType: string
		lineageTag: 73216fc3-23fc-4d8f-bac8-0afe416ac5aa
		summarizeBy: none
		sourceColumn: Mês
		sortByColumn: 'Mês Nº'

	column Ano-Mês
		dataType: string
		lineageTag: b61bb9aa-4b3a-4ad9-ae36-ed8bf414db51
		summarizeBy: none
		sourceColumn: Ano-Mês

	partition calendario = m
		mode: import
		source =
				let
					StartDate = #date(2016, 9, 1),
					EndDate = #date(2018, 10, 31),
					Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
					AsTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
					Typed = Table.TransformColumnTypes(AsTable, {{"Date", type date}}),
					Year = Table.AddColumn(Typed, "Ano", each Date.Year([Date]), Int64.Type),
					MonthNumber = Table.AddColumn(Year, "Mês Nº", each Date.Month([Date]), Int64.Type),
					MonthName = Table.AddColumn(MonthNumber, "Mês", each Text.Proper(Date.MonthName([Date], "pt-BR")), type text),
					YearMonth = Table.AddColumn(MonthName, "Ano-Mês", each Date.ToText([Date], "yyyy-MM"), type text)
				in
					YearMonth

	annotation PBI_ResultType = Table

