table orders

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id

	column order_status
		dataType: string
		summarizeBy: none
		sourceColumn: order_status

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: order_approved_at

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

	column order_purchase_date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: order_purchase_date

		annotation UnderlyingDateTimeDataType = Date

	partition orders = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "olist_orders_dataset_clean.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					EmptyToNull = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					Typed = Table.TransformColumnTypes(EmptyToNull, {{"order_id", type text}, {"customer_id", type text}, {"order_status", type text}, {"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}}, "en-US"),
					PurchaseDate = Table.AddColumn(Typed, "order_purchase_date", each DateTime.Date([order_purchase_timestamp]), type date)
				in
					PurchaseDate

	annotation PBI_ResultType = Table
