table order_items

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id

	column order_item_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: order_item_id

	column product_id
		dataType: string
		summarizeBy: none
		sourceColumn: product_id

	column seller_id
		dataType: string
		summarizeBy: none
		sourceColumn: seller_id

	column shipping_limit_date
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: shipping_limit_date

	column price
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: price

	column freight_value
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: freight_value

	partition order_items = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "olist_order_items_dataset_clean.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"order_id", type text}, {"order_item_id", Int64.Type}, {"product_id", type text}, {"seller_id", type text}, {"shipping_limit_date", type datetime}, {"price", type number}, {"freight_value", type number}}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
