table order_reviews

	column review_id
		dataType: string
		summarizeBy: none
		sourceColumn: review_id

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id

	column review_score
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: review_score

	column review_comment_title
		dataType: string
		summarizeBy: none
		sourceColumn: review_comment_title

	column review_comment_message
		dataType: string
		summarizeBy: none
		sourceColumn: review_comment_message

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: review_creation_date

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: review_answer_timestamp

	partition order_reviews = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "olist_order_reviews_dataset_clean.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					EmptyToNull = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					Typed = Table.TransformColumnTypes(EmptyToNull, {{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}}, "en-US")
				in
					Typed

	annotation PBI_ResultType = Table
